# Generated by Django 4.1.3 on 2024-07-09 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0003_lead_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ("name",)},
        ),
    ]
